### ISSUE TITLE
I was logged out immediately after I logged in

### ISSUE THREAD

**Issue by ghost** [alfathdirk/LIN3-TCR#30]
It appeared this

Traceback (most recent call last):
  File "tcr.py", line 9, in <module>
    cl.login(qr=True)
  File "/data/data/com.termux/files/home/LIN3-TCR/LINETCR/LineApi.py", line 44, in login
    self.Poll = Poll(self.authToken)
  File "/data/data/com.termux/files/home/LIN3-TCR/LINETCR/Api/Poll.py", line 35, in __init__
    self.rev = self.client.getLastOpRevision()
  File "/data/data/com.termux/files/home/LIN3-TCR/LINETCR/Api/../lib/curve/LineService.py", line 9884, in getLastOpRevision
    return self.recv_getLastOpRevision()
  File "/data/data/com.termux/files/home/LIN3-TCR/LINETCR/Api/../lib/curve/LineService.py", line 9907, in recv_getLastOpRevision
    raise result.e
curve.ttypes.TalkException: TalkException(parameterMap=None, reason='LOG_OUT', code=8)

**Comment by Fayyaz009** [comment]
Same error here kindly update id and help your fans
